### ISSUE TITLE
Integration with Carbon Aware SDK

### ISSUE THREAD

**Issue by srini1978** [Green-Software-Foundation/if#216]
Carbon Aware SDK is a mature GSF project and today it provides regional carbon intensity values given a region and enables time shifting and region shifting.

In a sense it is a model very similar to how Watt Time or Electricity Maps function which are also models. This issue is a proposal to build an impl file and a sample case study where we can integrate Impact framework with carbon aware SDK as a model and look at the results.

@jawache  @jmcook1186  @navveenb

**Comment by jawache** [comment]
Thanks @srini1978 is your thinking to create a model which can be used just like the way the WattTime model is currently being used in the demo pipeline? So a casdk model which can drop in replace say a WattTime model?

**Comment by srini1978** [comment]
@jawache  yes you are right

**Comment by jawache** [comment]
Discussed on call:
- This can be something the casdk team can develop themselves.
- Perhaps wait for our documentation to mature to the point where it's easier to follow a step by step process to make a model.
- This also might wait until after models can be loaded dynamicly

**Comment by jmcook1186** [comment]
Awaiting call with C-SDK team (was scheduled for today but now cancelled)

**Comment by jmcook1186** [comment]
Just to further specify what is required here:
we want to wrap C-SDK API calls in  aIF plugin, so that we can include C-SDK in a normal IF pipeline. 

The first objective would be for a model to make a request to the C-SDK `GET emissions/bylocation` endpoint passing the `location` value provided in `inputs` and add the returned value to `inputs['grid-emissions`]`

The second objective would be for a model to make a request to the C-SDK `GET emissions/bylocation/best` endpoint and add the returned value to `inputs['best-region`]`

AFAICT there is no public hosted endpoint for these - the tool relies on running a local server or locally installing and invoking the CLI. This might be somethign we can handle via the existing `Shell` model

**Comment by jawache** [comment]
FYI I would hold off on creating anything here 😄 the UCL grads are building something related to this and this could easily be seeded (and had been seeded) in the hackathon repo as an idea someone could build.

I'm guessing we'll get several hackathon submissions implementing this approach.
