### ISSUE TITLE
Handling slow/failed API requests in models

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#326]

**Comment by srini1978** [comment]
When calling REST APIs or external APIs, there are bound to be failures due to throtting on the API side, poor network connectivity, network failures, timeouts, DoS attacks. 

Since our impl files is a consolidated file of all inputs and there are chances of either 1) Many calls to the same API 2) Calls to many APIs we should have provision in place on our side to graciously handle these exceptions. Some thoughts:

1. Let us implement transient error handling through retries or backoff mechanisms. Some patterns provided here -https://learn.microsoft.com/en-us/azure/architecture/best-practices/transient-faults
2. Are there any provisions in our framework to cache previous responses. For example we can build a mechanism that can cache previous responses and if the input parameters are a 70-80% match with the previous time this API was called, can we return the responses received previously rather than returning null.

In either or both of the above suggestions, we should have a configuration framework on IF side to handle retry counts, storing previous responses, caching framework. However a call can be made on whether we spend effort to do this or not depending on the market of all APIs we want to call.

What i mean by the above: today Azure monitoring REST API is a candidate API. Based on our research and discussions with customers and their case studies have we found scenarios where APIs need to be leveraged for the core computation pipeline.

For example, some statistics that we can look at. How many models or model plugins are only API based?  Do these models have a non-API remote procedure based alternate as well?

FYI @jmcook1186  @jawache  @navveenb

**Comment by jmcook1186** [comment]
Thanks @srini1978 this is very helpful. Also tagging @narekhovhannisyan - I think he will be interested in this discussion too.

Right now the models that rely on external API calls are all in `if-unofficial-models`. They are: 

`azure-importer`
`watttime`
`boavizta`

Boavizta has a Rust SDK - on first look it seems feasible to expose the necessary functions locally instead of relying on their API server.

Watttime is closed source, so we are reliant upon their API server for their data.

For Azure, it seems necessary to use the REST API, but defer to your expertise on that.

**Comment by jawache** [comment]
I think most of this logic should be in the the model itself, but we can have clever exceptions for helping things out.

I also think it makes sense to run models *serially* and not in *parallel*. It might be slower but it's a lot easier to code and keep bug free on the framework side also makes logic inside models easier. If your making API calls inside models, and we run models in parallel, wed thrash your API, you couldn't do any API mgmt inside the model since you'd have no idea how many other models are calling the same API same time!

One approach could be of there is a timeout/throttle event the model throws a TimeOut exception with a retryIn parameter. The framework could just call the whole model again in retryIn seconds.

It should also be a cli Param, I may want the cli never to retry, or I may want a max time to wait after which kill the script. --max-retry-seconds defaults to something low, even 0 second?
