### ISSUE TITLE
Question on cloud instance metadata

### ISSUE THREAD

**Issue by srini1978** [Green-Software-Foundation/if#328]
Will cloud instance metadata plugin return Embodied emissions value for the physical processor by tapping into CCF co-efficients?

FYI @jmcook1186

**Comment by jmcook1186** [comment]
Hi @srini1978 - no the cloud instance metadata does not return embodied carbon by itself. You would use it in a pipeline with the SCI-M plugin to estimate embodied emissions, or just use the CCF plugin.

**Comment by jmcook1186** [comment]
oh I see what you mean - yes, CCF is the only model that can get embodied emissions for some given hardware, but we do not execute it as part of the `cloud-instance-metadata` model. We have mostly been thinking about `cloud-instance-metadata` as a way to get standardized hardware info to feed `tdp-finder` so that we can look up the thermal design power for a given chip. 

We maintain our own instances of the CCF embodied-carbon data, so it is possible to streamline things so that the lookup is done in the same model as the instance metadata. Personally I favour separating the concerns, but would be happy to open the conversation to see what others think.
