### ISSUE TITLE
👍🏼 Set up CI/CD to trigger automated tests for PRs

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#621]
**Sub of:** #629  -> #650 

**What**
Set up CI/CD to trigger automated tests that must pass for a PR to be mergeable

**Why**
As a core developer I want to quickly see whether proposed changes pass our tests. This will speed up the review process and make us more confident int he changes we are merging in.

**Context**
We are designing new automated tests to ensure the integrity of the IF source code. We want to make this part of the CI/CD process so all PRs are held to the same standards before being merged, but without adding more work for the reviewer. CI/CD is the solution to this problem.

**Prerequisites**
- #592 
- #615 
- #638 

**SoW**
- [ ] Update CI/CD script to include unit tests , integration tests and regression tests
- [ ] **ON HOLD UNTIL SOMEONE NEEDS THIS**: Either publish the GitHub action or document it on if-docs to the so 3rd party plugin developers can add the same functionality to their repos.
- [ ]  **ON HOLD UNTIL SOMEONE NEEDS THIS**: Update the sample plugin template repos so people can easily add this in.

**Acceptance criteria**
- [ ] A GitHub action that runs on every PR to if and runs `if-check` on the manifest files folder in if.

**GIVEN** a user is developing against IF
**AND** IF has a folder called `manifests` full of manifest test files
**AND** all of the manifest files are passing.
**WHEN** the user creates a PR
**THEN** a GitHub action runs which runs `if-check --folder /path/to/manifests`
**AND** the PR is marked as passing this check.

**GIVEN** a user is developing against IF
**AND** IF has a folder called `manifests` full of manifest test files
**AND** one of the manifest files is failing.
**WHEN** the user creates a PR
**THEN** a GitHub action runs which runs `if-check --folder /path/to/manifests`
**AND** the PR is marked as failing this check.
**AND** the PR has a link the developer can click to find out which manifest is failing

**Comment by jawache** [comment]
@jmcook1186 specifically this issue is related to the creation of both the manifest files folder (#615) and the if verify tool (#638), it's dependent on both of them being completed first.

**Acceptance Criteria**
- [ ] A GitHub action that runs on every PR to `if` and runs `if-verify` on the manifest files folder in `if`.
- If the if-verify tool returns an error code then this marks the PR as failing, otherwise passing.
- The PR message should contain a link which people can click to see the GH action logs and quickly determine which manifest is causing the failure (no need for a fancy UI, just a link to the GH action logs is fine)
- The PR should be marked as failing if the if-verify tool fails, the PR can't be merged.
- [ ] Document the GH action in `if-docs` so 3rd party plugin developers can run if-verify on their manifest files in their repos and have the same functionality we do in our main repo.

With the issue updated to the new format and the above acceptance criteria you can mark this issue as 👍🏽 from me.

**Comment by jmcook1186** [comment]
ok @jawache  updated, awaiting your approval

**Comment by jawache** [comment]
Done, so we're on the same page, this particular issue needs refinement by the dev to list out the work items in SoW

**Comment by zanete** [comment]
some investigation is needed to link the manifest files to the GH action
