### ISSUE TITLE
Document how we label our issues and expectations for each label.

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#630]
Sub of #657 

**What**
Include documentation in our `github-processes.md` document that explains what labels we use across our repositories, how they should be interpreted, and the processes that determine when they are applied.

**why**

As a user I want clear guidance to understand what the labels on various issues and PRs mean and to help me navigate the project and make useful contributions.

**Relevant links:**
- Labels required by PM process: [https://www.notion.so/grnsft/Internal-Project-Protocol-6b8a9e881ed942df9a81a60aeecfd998#cad9f95e90894cb284c0d2e6bac8b059](https://www.google.com/url?q=https://www.notion.so/grnsft/Internal-Project-Protocol-6b8a9e881ed942df9a81a60aeecfd998%23cad9f95e90894cb284c0d2e6bac8b059&sa=D&source=calendar&ust=1717857190510181&usg=AOvVaw3zizddruwproxA3pzODaCb)
- labels documented in the IF repos: [https://www.notion.so/grnsft/Internal-Project-Protocol-6b8a9e881ed942df9a81a60aeecfd998#cad9f95e90894cb284c0d2e6bac8b059](https://www.google.com/url?q=https://www.notion.so/grnsft/Internal-Project-Protocol-6b8a9e881ed942df9a81a60aeecfd998%23cad9f95e90894cb284c0d2e6bac8b059&sa=D&source=calendar&ust=1717857190510181&usg=AOvVaw3zizddruwproxA3pzODaCb)

**Acceptance critera**

- [ ] `if/github-processes.md` contains a table containing each of our issue labels with a description and an explanation of when it is applied or link to relevant process documentation

**Statement of work**
- [x] review existing labels and identify any that can be added/removed
- [ ] check labels are synchronized across `if`, `if-plugins`, `if-unofficial-plugins` and `if-plugin-template`
- [ ] add table to `if/github-processes.md` detailing the labels

**Comment by jmcook1186** [comment]
@zanete would appreciate your input on this as you are taking over the PM side of things and may have ideas for which labels are useful and which ones can be removed.

**Comment by zanete** [comment]
@jmcook1186 Thanks, sure thing, I will plan this in one of the coming weeks after we've had a couple of sprint plans and a good solid 2-3 weeks of trialing the new process. Given the priority is set to low, that shouldn't be a problem, should it? Let me know if you believe this is blocking anything and I will revisit

**Comment by zanete** [comment]
Label | Used by | Description
-- | -- | --
blocked | all | The issue is blocked and cannot proceed.
bug |  all | Error, flaw or fault
draft | all | The issue is still being written, no need to respond or action on anything.
good-first-issue | all | This issue is a good one for someone looking to get involved with this project/initiative.
needs-response | all | The issue has stalled because someone isn’t responding.
agenda | core team | Use for any meeting agenda or minutes issue.
EPIC | core team| Used to denote an issue that represents a whole epic
initiative | core team | A helper label, needed for GSF internal processes
i-summary | core team | A helper label, needed for GSF internal processes
i-milestone | core team | A helper label, needed for GSF internal processes
project-update | core team | Used to flag project progress updates
