### ISSUE TITLE
Implement manifest Visualiser

### ISSUE THREAD

**Issue by zanete** [Green-Software-Foundation/if#981]
**why**: Sub of #951 
**What**: The implementation of Manifest visualiser

Blocked by #954 

**Scope of work:**
- [x] Implement as per design in #954 
- [x] Embed in the IF website 
- [ ] Acceptance test with various manifests

**Comment by zanete** [comment]
Plan is that by the end of the week we should get a not styled version of the chart and the data table to ensure that the manifest is parsed correctly, and after confirmation that's all working will work on the style. 
cc @jmcook1186 @jawache

**Comment by zanete** [comment]
**Capturing the status on the weekly call:**
- @osamajandali has made progress (Table and graph are showing data) but need to recode the parser after discussing nesting with @jmcook1186 
- Expecting the non-styled version in a couple of days.

**Comment by osamajandali** [comment]
The unstyled version is ready for testing. You can access it here: [Visualizer](https://if-visualizer.vercel.app/).

Let's ensure we test thoroughly and identify any bugs or errors that might arise.

The file URL passed can be a GitHub raw file URL, a direct URL to a file, or a locally served file. For example, we can pass `http://localhost:5500/demo-output.yaml` without any issues. This is possible because everything from parsing to visuals happens on the client side, allowing us to serve local files directly without any security concerns.

Feel free to share your thoughts!

cc: @zanete @jmcook1186 @jawache

**Comment by jawache** [comment]
Oh wow @osamajandali , if we can load localhost files from a hosted website that's amazing, will check it out tomorrow!
